<?php

/**
 * @file
 * Install, update and uninstall functions for the Test module module.
 */

/**
 * Implements hook_install().
 */
function test_module_install() {
  \Drupal::messenger()->addStatus(__FUNCTION__);
}

/**
 * Implements hook_uninstall().
 */
function test_module_uninstall() {
  \Drupal::messenger()->addStatus(__FUNCTION__);
}

/**
 * Implements hook_schema().
 */
function test_module_schema() {
  $schema['test_module_example'] = [
    'description' => 'Tabla de descripción.',
    'fields' => [
      'id' => [
        'type' => 'serial',
        'not null' => TRUE,
        'description' => 'Clave primaria: ID de registro único.',
      ],
      'last_name' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'description' => 'Apellido.',
      ],
      'name' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'description' => 'Nombre.',
      ],
      'document_type' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'description' => 'Tipo de documento.',
      ],
      'document' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'description' => 'Documento.',
      ],
      'email' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'description' => 'Correo electrónico.',
      ],
      'phone' => [
        'type' => 'varchar',
        'length' => 20,
        'not null' => TRUE,
        'description' => 'Teléfono.',
      ],
      'country' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'description' => 'País.',
      ],
    ],
    'primary key' => ['id'],
  ];

  return $schema;
}



/**
 * Implements hook_requirements().
 */
function test_module_requirements($phase) {
  $requirements = [];

  if ($phase == 'runtime') {
    $value = mt_rand(0, 100);
    $requirements['test_module_status'] = [
      'title' => t('Test module status'),
      'value' => t('Test module value: @value', ['@value' => $value]),
      'severity' => $value > 50 ? REQUIREMENT_INFO : REQUIREMENT_WARNING,
    ];
  }

  return $requirements;
}
